Intro Code
cmsc436/MSTestSuite pull request #6
Opened 2017-04-25 01:50 UTC by JoshLehman

-Integrated michelle's old intro code
-Added entries in UI for DOB and Gender
-Adds UI information into user manager

2017-04-25 02:22 UTC, 0queue commented
Initial notes: style changes, remove unnecessary xml (layouts, random strings), restore color blind mode

2017-04-25 12:42 UTC, 0queue commented on app/src/main/AndroidManifest.xml
> +        android:theme="@style/AppTheme">
Should be AppTheme.ColorBlind

2017-04-25 12:42 UTC, 0queue commented on app/src/main/AndroidManifest.xml
> +            android:exported="false"></service>
Let's get rid of these empty tags while we're at it

2017-04-25 12:43 UTC, 0queue commented on app/src/main/java/edu/umd/cmsc436/mstestsuite/IntroActivity.java
> +            Log.i("Login", "There was a user");
Get rid of unnecessary logs

2017-04-25 12:43 UTC, 0queue commented on app/src/main/java/edu/umd/cmsc436/mstestsuite/IntroActivity.java
> +                int current = getItem(+1);
That call to getItem(+1) can just be getItem(1)

2017-04-25 12:44 UTC, 0queue commented on app/src/main/java/edu/umd/cmsc436/mstestsuite/IntroActivity.java
> +        Log.i("Log", "USER Added");
(Log again)

2017-04-25 12:46 UTC, 0queue commented on app/src/main/res/layout/activity_intro.xml
> +<?xml version="1.0" encoding="utf-8"?>
Whole file could use auto-format (Ctrl-Alt-L, or something similar on Mac)

2017-04-25 12:46 UTC, 0queue commented on app/src/main/res/layout/activity_intro_1.xml
> +<?xml version="1.0" encoding="utf-8"?>
(Auto format)

2017-04-25 12:47 UTC, 0queue commented on app/src/main/res/layout/activity_intro_2.xml
> +<?xml version="1.0" encoding="utf-8"?>
(Auto format)

2017-04-25 12:47 UTC, 0queue commented on app/src/main/res/layout/activity_intro_3.xml
> +<?xml version="1.0" encoding="utf-8"?>
This file should be combined with activity_intro_1, so there are only two intro layouts

2017-04-25 12:49 UTC, 0queue commented on app/src/main/res/values/colors.xml
> +    <color name="screen1">#E3F2FD</color>
All of these new colors should probably be changed, to a black/white or very light gray, with the dots being colorAccent436 and colorAccentLight436

2017-04-25 12:50 UTC, 0queue commented on app/src/main/res/values/dimens.xml
> +    <dimen name="fab_margin">16dp</dimen>
Only fab_margin is being used, and not even for a fab, so these should be removed

2017-04-25 12:50 UTC, 0queue commented on app/src/main/res/values/strings.xml
> +    <string name="tap_start_text">Tap to start</string>
Unnecessary strings

2017-04-25 12:52 UTC, 0queue commented on app/src/main/AndroidManifest.xml
> +    package="edu.umd.cmsc436.mstestsuite">
Should also be auto formatted

2017-04-25 12:52 UTC, 0queue requested changes
Clean up of some leftovers from the other project, and then style changes.  Also, combine the last and first intro layouts, they don't need to be separate

2017-04-30 23:10 UTC, JoshLehman commented on app/src/main/res/values/dimens.xml
> +    <dimen name="fab_margin">16dp</dimen>
We need fab_margin

2017-04-30 23:11 UTC, JoshLehman commented on app/src/main/res/values/strings.xml
> +    <string name="tap_start_text">Tap to start</string>
we need handedness

2017-05-01 02:34 UTC, 0queue requested changes
Looks a lot better, thanks!  Just three tweaks and that'll be it!

2017-05-01 02:34 UTC, 0queue commented on app/src/main/java/edu/umd/cmsc436/mstestsuite/IntroActivity.java
> +import android.view.inputmethod.InputMethodManager;
Unused imports (Ctrl-Alt-O on the file to remove)

2017-05-01 02:34 UTC, 0queue commented on app/src/main/java/edu/umd/cmsc436/mstestsuite/IntroActivity.java
>      protected void onCreate(final Bundle savedInstanceState) {
Just one last style change: Change the status bar color to white with the line `getWindow().setStatusBarColor(ContextCompat.getColor(this, android.R.color.white));` (It looks really slick)

2017-05-01 02:34 UTC, 0queue commented on app/src/main/res/layout/activity_intro.xml
> +
Not sure why there's a Toolbar here, it can be deleted

2017-05-01 20:03 UTC, 0queue approved these changes

2017-05-01 20:03 UTC, merged